# Generated by Django 3.0 on 2019-12-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlatterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('small', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SaladType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('small', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Pizza'},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizzaType',
            new_name='regular',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('SM', 'small'), ('LG', 'large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'small'), ('LG', 'large')], default='SM', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('addons', models.ManyToManyField(to='orders.AddOn')),
                ('name', models.ManyToManyField(to='orders.SubType')),
            ],
            options={
                'verbose_name_plural': 'Subs',
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('name', models.ManyToManyField(to='orders.SaladType')),
            ],
        ),
        migrations.CreateModel(
            name='Platters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'small'), ('LG', 'large')], default='SM', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('name', models.ManyToManyField(to='orders.PlatterType')),
            ],
            options={
                'verbose_name_plural': 'Platters',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('name', models.ManyToManyField(to='orders.PastaType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.ManyToManyField(to='orders.Pasta')),
                ('pizza', models.ManyToManyField(to='orders.Pizza')),
                ('platter', models.ManyToManyField(to='orders.Platters')),
                ('salad', models.ManyToManyField(to='orders.Salad')),
                ('subs', models.ManyToManyField(to='orders.Subs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
