# Generated by Django 3.0 on 2019-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191226_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platters',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
