# Generated by Django 3.0 on 2019-12-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191226_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='platters',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=2),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=2),
        ),
    ]
