# Generated by Django 3.0 on 2019-12-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191226_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'pizza'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='platter',
            new_name='platters',
        ),
    ]
